# Lab 2.1 — Makefile build system
#
# Work through the phases in order:
#   Phase 1 — explicit rules  →  get a working build (~30 min)
#   Phase 2 — pattern rule    →  clean up and scale (~20 min)
#   Phase 3 — utility targets →  complete the interface (~20 min)
#
# Reference: docs/make_guide.md
# Warm-up:   docs/exercises/README.md

# --- Toolchain ---------------------------------------------------------------
CC      = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE    = arm-none-eabi-size

# --- Project -----------------------------------------------------------------
TARGET   = lab2
BUILDDIR = output
SRCDIR   = src
INCDIR   = inc

# --- Flags -------------------------------------------------------------------
CPU_FLAGS    = -mcpu=cortex-m4 -mthumb -mfloat-abi=soft
EXTRA_CFLAGS ?=
CFLAGS       = $(CPU_FLAGS) -O0 -g3 -ffreestanding -Wall -Wextra \
               -I$(INCDIR) $(EXTRA_CFLAGS) \
               -MMD -MP
# -MMD: generate output/%.d alongside each .o listing #included headers.
# -MP:  add a dummy rule per header so Make does not error if one is deleted.
# The -include below loads those .d files automatically.
LDFLAGS  = -nostdlib -T linker/stm32f412zg.ld $(CPU_FLAGS)
AS_FLAGS = $(CPU_FLAGS) -g3

# --- Output files (provided — do not change) ---------------------------------
ELF = $(BUILDDIR)/$(TARGET).elf
BIN = $(BUILDDIR)/$(TARGET).bin
HEX = $(BUILDDIR)/$(TARGET).hex

# Make's default goal is the first real target in the file.
# Declaring it explicitly here keeps 'all' as the default even though
# the $(BUILDDIR) helper rule is defined earlier in the file.
.DEFAULT_GOAL := all

# =============================================================================
# PHASE 1 — Explicit rules
# Goal: make all produces output/lab2.elf, output/lab2.bin, output/lab2.hex
# Verify with milestones M1 and M2 from README.md
# =============================================================================

# P1.1 — List the two C source files (paths relative to the repo root).
#         Example: SRCS = src/foo.c src/bar.c
SRCS = src/gpio.c src/main.c

# Assembly startup — provided, do not change.
ASM_SRC = startup/startup_stm32f412zg.s

# P1.2 — Set the assembly object path: same filename as ASM_SRC but inside
#         $(BUILDDIR)/ and with .o extension instead of .s
ASM_OBJ = $(BUILDDIR)/startup_stm32f412zg.o

# P1.3 — Default target: "all" must depend on $(ELF), $(BIN), and $(HEX).
#         Syntax: all: dep1 dep2 dep3
#         Warning: leaving this line as "all:" with no dependencies makes
#         Make silently succeed and build nothing.
all: $(ELF) $(BIN) $(HEX)

# --- Output directory --------------------------------------------------------
# Provided — do not change. Creates output/ before any compile rule needs it.
# The | syntax means: build this first, but its timestamp does not trigger rebuilds.
$(BUILDDIR):
	mkdir -p $@

# P1.4 — Compile the assembly startup file.
#         Target:       $(ASM_OBJ)
#         Dependencies: $(ASM_SRC) | $(BUILDDIR)
#         Recipe:       $(CC) $(AS_FLAGS) -c $< -o $@
#
# YOUR RULE HERE
$(ASM_OBJ): $(ASM_SRC) | $(BUILDDIR)
	$(CC) $(AS_FLAGS) -c $< -o $@

# P1.5 — Compile src/gpio.c into output/gpio.o  (explicit rule).
#         Target:       output/gpio.o
#         Dependencies: src/gpio.c | $(BUILDDIR)
#         Recipe:       $(CC) $(CFLAGS) -c $< -o $@
#
# YOUR RULE HERE
# $(BUILDDIR)/gpio.o: $(SRCDIR)/gpio.c | $(BUILDDIR)
# 	$(CC) $(CFLAGS) -c $< -o $@

# P1.6 — Compile src/main.c into output/main.o  (explicit rule).
#         Same form as P1.5 but for main.c.
#
# YOUR RULE HERE
# $(BUILDDIR)/main.o: $(SRCDIR)/main.c | $(BUILDDIR)
# 	$(CC) $(CFLAGS) -c $< -o $@

# P1.7 — Link all objects into the ELF.
#         Target:       $(ELF)
#         Dependencies: output/gpio.o output/main.o $(ASM_OBJ)
#         Recipe:       $(CC) $(LDFLAGS) -o $@ $^
#                       ($^ = all dependencies listed above)
#
# YOUR RULE HERE
# $(ELF): $(BUILDDIR)/gpio.o $(BUILDDIR)/main.o $(ASM_OBJ)
# 	$(CC) $(LDFLAGS) -o $@ $^

# P1.8 — Produce the binary and hex files from the ELF.
#         $(BIN) rule: $(OBJCOPY) -O binary $< $@
#         $(HEX) rule: $(OBJCOPY) -O ihex   $< $@
#
# YOUR TWO RULES HERE
$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@
$(HEX): $(ELF)
	$(OBJCOPY) -O ihex $< $@

# =============================================================================
# PHASE 2 — Refactor: replace explicit C rules with a pattern rule
# Goal: one rule handles any number of .c files; Makefile shrinks
# When Phase 2 is complete, DELETE the explicit rules P1.5 and P1.6 above.
# Verify with milestone M5 from README.md (incremental rebuild)
# =============================================================================

# Automatic header dependencies — provided, do not change.
# Loads the .d files generated by -MMD so that touching a .h triggers recompilation.
-include $(wildcard $(BUILDDIR)/*.d)

# P2.1 — Derive OBJS from SRCS using a substitution reference.
#         Replace the src/%.c pattern with output/%.o
#         Hint: $(SRCS:$(SRCDIR)/%.c=$(BUILDDIR)/%.o)
OBJS = $(SRCS:$(SRCDIR)/%.c=$(BUILDDIR)/%.o)

# P2.2 — Replace the two explicit C rules with one static pattern rule.
#         Steps (do them together before running make — having both the explicit
#         rules and the pattern rule active at the same time causes warnings):
#           1. Delete the explicit rules P1.5 and P1.6 above.
#           2. Write the pattern rule below.
#           3. Update P1.7 to list $(OBJS) instead of the two hardcoded paths.
#           4. Run make — output should be identical to Phase 1.
#
#         Form:
#           $(OBJS): $(BUILDDIR)/%.o : $(SRCDIR)/%.c | $(BUILDDIR)
#               $(CC) $(CFLAGS) -c $< -o $@
#
# YOUR RULE HERE
# add P1.7
$(ELF): $(OBJS) $(ASM_OBJ)
	$(CC) $(LDFLAGS) -o $@ $^

$(OBJS): $(BUILDDIR)/%.o : $(SRCDIR)/%.c | $(BUILDDIR)
	$(CC) $(CFLAGS) -c $< -o $@

# =============================================================================
# PHASE 3 — Utility targets
# Goal: complete the build interface
# =============================================================================

# P3.1 — "clean": remove the entire $(BUILDDIR)/ directory.
#         Recipe: rm -rf $(BUILDDIR)
#
# YOUR RULE HERE
clean:
	rm -rf $(BUILDDIR)

# P3.2 — "size": depends on $(ELF), prints the firmware size.
#         Recipe: $(SIZE) $<
#
# YOUR RULE HERE
size: $(ELF)
	$(SIZE)	$<

# P3.3 — "flash": depends on $(ELF), programs the board.
#         Recipe: bash scripts/flash.sh
#
# YOUR RULE HERE
flash: $(ELF)
	bash scripts/flash.sh

# --- Help (provided — do not change) -----------------------------------------
help:
	@echo ""
	@echo "  Targets:"
	@echo "    all    Build $(TARGET).elf, .bin, .hex  (default)"
	@echo "    clean  Remove $(BUILDDIR)/"
	@echo "    flash  Flash firmware via ST-LINK"
	@echo "    size   Print firmware size report"
	@echo "    help   Show this message"
	@echo ""

# P3.4 — Declare all non-file targets as .PHONY.
#         List: all clean flash size help
#
# YOUR LINE HERE
.PHONY: all clean flash size help
